version: "2"
name: Test Import Stack
canonical: test_import_stack
author: rboatwright
status: private
description: Test Import Stack
image: ""
keywords:
- 'test '
- provider:azure
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
