version: "2"
name: AKS - rg-dev-aks
canonical: aks_-_rg-dev-aks
author: rboatwright
status: private
description: AKS - rg-dev-aks
image: ""
keywords:
- rg-dev-aks
- provider:azure
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      aks_-_rg-dev-aks:
        destination: ($ project $)/terraform/($ environment $)/aks_-_rg-dev-aks.tf
        path: terraform/default/aks_-_rg-dev-aks.tf.sample
