resource "azurerm_container_registry" "_subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev" {
  encryption {
    identity_client_id = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_encryption_0_identity_client_id
    key_vault_key_id   = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_encryption_0_key_vault_key_id
  }

  export_policy_enabled         = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_export_policy_enabled
  location                      = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_location
  name                          = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_name
  network_rule_bypass_option    = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_network_rule_bypass_option
  public_network_access_enabled = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_public_network_access_enabled
  resource_group_name           = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_resource_group_name
  retention_policy {
    days = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_retention_policy_0_days
  }

  sku = var.azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_sku
}

resource "azurerm_kubernetes_cluster" "_subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev" {
  auto_scaler_profile {
    empty_bulk_delete_max            = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_empty_bulk_delete_max
    expander                         = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_expander
    max_graceful_termination_sec     = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_max_graceful_termination_sec
    max_node_provisioning_time       = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_max_node_provisioning_time
    max_unready_nodes                = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_max_unready_nodes
    max_unready_percentage           = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_max_unready_percentage
    new_pod_scale_up_delay           = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_new_pod_scale_up_delay
    scale_down_delay_after_add       = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_delay_after_add
    scale_down_delay_after_delete    = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_delay_after_delete
    scale_down_delay_after_failure   = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_delay_after_failure
    scale_down_unneeded              = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_unneeded
    scale_down_unready               = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_unready
    scale_down_utilization_threshold = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_utilization_threshold
    scan_interval                    = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scan_interval
    skip_nodes_with_system_pods      = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_skip_nodes_with_system_pods
  }

  azure_active_directory_role_based_access_control {
    admin_group_object_ids = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_azure_active_directory_role_based_access_control_0_admin_group_object_ids
    managed                = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_azure_active_directory_role_based_access_control_0_managed
    tenant_id              = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_azure_active_directory_role_based_access_control_0_tenant_id
  }

  azure_policy_enabled = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_azure_policy_enabled
  default_node_pool {
    enable_auto_scaling          = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_enable_auto_scaling
    kubelet_disk_type            = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_kubelet_disk_type
    max_count                    = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_max_count
    max_pods                     = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_max_pods
    min_count                    = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_min_count
    name                         = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_name
    node_count                   = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_node_count
    only_critical_addons_enabled = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_only_critical_addons_enabled
    orchestrator_version         = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_orchestrator_version
    os_disk_size_gb              = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_os_disk_size_gb
    os_disk_type                 = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_os_disk_type
    os_sku                       = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_os_sku
    type                         = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_type
    vm_size                      = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_vm_size
  }

  dns_prefix = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_dns_prefix
  identity {
    identity_ids = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_identity_0_identity_ids
    type         = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_identity_0_type
  }

  kubelet_identity {
    client_id                 = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_kubelet_identity_0_client_id
    object_id                 = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_kubelet_identity_0_object_id
    user_assigned_identity_id = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_kubelet_identity_0_user_assigned_identity_id
  }

  kubernetes_version     = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_kubernetes_version
  local_account_disabled = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_local_account_disabled
  location               = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_location
  name                   = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_name
  network_profile {
    dns_service_ip     = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_dns_service_ip
    docker_bridge_cidr = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_docker_bridge_cidr
    ip_versions        = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_ip_versions
    load_balancer_profile {
      managed_outbound_ip_count = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_load_balancer_profile_0_managed_outbound_ip_count
    }

    load_balancer_sku = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_load_balancer_sku
    network_plugin    = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_network_plugin
    outbound_type     = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_outbound_type
    pod_cidr          = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_pod_cidr
    service_cidr      = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_service_cidr
  }

  node_resource_group = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_node_resource_group
  oms_agent {
    log_analytics_workspace_id = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_oms_agent_0_log_analytics_workspace_id
  }

  public_network_access_enabled     = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_public_network_access_enabled
  resource_group_name               = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_resource_group_name
  role_based_access_control_enabled = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_role_based_access_control_enabled
  run_command_enabled               = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_run_command_enabled
  sku_tier                          = var.azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_sku_tier
}

resource "azurerm_kubernetes_cluster_node_pool" "_subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system" {
  enable_auto_scaling   = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_enable_auto_scaling
  kubelet_disk_type     = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_kubelet_disk_type
  kubernetes_cluster_id = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_kubernetes_cluster_id
  max_count             = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_max_count
  max_pods              = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_max_pods
  min_count             = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_min_count
  mode                  = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_mode
  name                  = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_name
  node_count            = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_node_count
  node_taints           = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_node_taints
  orchestrator_version  = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_orchestrator_version
  os_disk_size_gb       = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_os_disk_size_gb
  os_disk_type          = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_os_disk_type
  os_sku                = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_os_sku
  os_type               = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_os_type
  priority              = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_priority
  scale_down_mode       = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_scale_down_mode
  spot_max_price        = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_spot_max_price
  vm_size               = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_vm_size
}

resource "azurerm_kubernetes_cluster_node_pool" "_subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user" {
  enable_auto_scaling   = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_enable_auto_scaling
  kubelet_disk_type     = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_kubelet_disk_type
  kubernetes_cluster_id = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_kubernetes_cluster_id
  max_count             = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_max_count
  max_pods              = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_max_pods
  min_count             = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_min_count
  mode                  = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_mode
  name                  = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_name
  node_count            = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_node_count
  orchestrator_version  = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_orchestrator_version
  os_disk_size_gb       = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_os_disk_size_gb
  os_disk_type          = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_os_disk_type
  os_sku                = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_os_sku
  os_type               = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_os_type
  priority              = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_priority
  scale_down_mode       = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_scale_down_mode
  spot_max_price        = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_spot_max_price
  vm_size               = var.azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_vm_size
}

