variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_encryption_0_identity_client_id" {
  default = ""
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_encryption_0_key_vault_key_id" {
  default = ""
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_export_policy_enabled" {
  default = true
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_location" {
  default = "eastus"
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_name" {
  default = "acrsoftdocsdev"
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_network_rule_bypass_option" {
  default = "AzureServices"
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_public_network_access_enabled" {
  default = true
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_resource_group_name" {
  default = "rg-dev-aks"
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_retention_policy_0_days" {
  default = 7
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_sku" {
  default = "Basic"
}

variable "azurerm_container_registry__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerregistry_registries_acrsoftdocsdev_tc_category" {
  default = "container"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_empty_bulk_delete_max" {
  default = "10"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_expander" {
  default = "random"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_max_graceful_termination_sec" {
  default = "600"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_max_node_provisioning_time" {
  default = "15m"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_max_unready_nodes" {
  default = 3
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_max_unready_percentage" {
  default = 45
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_new_pod_scale_up_delay" {
  default = "0s"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_delay_after_add" {
  default = "10m"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_delay_after_delete" {
  default = "10s"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_delay_after_failure" {
  default = "3m"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_unneeded" {
  default = "10m"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_unready" {
  default = "20m"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scale_down_utilization_threshold" {
  default = "0.5"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_scan_interval" {
  default = "10s"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_auto_scaler_profile_0_skip_nodes_with_system_pods" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_azure_active_directory_role_based_access_control_0_admin_group_object_ids" {
  default = ["2635a097-9a85-460d-a85d-a42e80e970b2"]
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_azure_active_directory_role_based_access_control_0_managed" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_azure_active_directory_role_based_access_control_0_tenant_id" {
  default = "65ee153b-5d1b-4029-873d-ac25eee38791"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_azure_policy_enabled" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_enable_auto_scaling" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_kubelet_disk_type" {
  default = "OS"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_max_count" {
  default = 3
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_max_pods" {
  default = 110
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_min_count" {
  default = 1
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_name" {
  default = "system"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_node_count" {
  default = 1
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_only_critical_addons_enabled" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_orchestrator_version" {
  default = "1.24.6"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_os_disk_size_gb" {
  default = 128
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_os_disk_type" {
  default = "Managed"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_os_sku" {
  default = "Ubuntu"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_type" {
  default = "VirtualMachineScaleSets"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_default_node_pool_0_vm_size" {
  default = "Standard_DS2_v2"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_dns_prefix" {
  default = "aks-dev"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_identity_0_identity_ids" {
  default = ["/subscriptions/a06ab73e-0da1-49d7-81cd-847d3e9618ac/resourceGroups/rg-dev-aks/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-aks-controlplane"]
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_identity_0_type" {
  default = "UserAssigned"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_kubelet_identity_0_client_id" {
  default = "fb38a494-39ab-4835-a379-3df0e0764c1e"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_kubelet_identity_0_object_id" {
  default = "50c453ac-2681-494d-8cbb-4a96378d6cd1"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_kubelet_identity_0_user_assigned_identity_id" {
  default = "/subscriptions/a06ab73e-0da1-49d7-81cd-847d3e9618ac/resourceGroups/rg-dev-aks-nodes/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-dev-agentpool"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_kubernetes_version" {
  default = "1.25.6"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_local_account_disabled" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_location" {
  default = "eastus"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_name" {
  default = "aks-dev"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_dns_service_ip" {
  default = "10.0.0.10"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_docker_bridge_cidr" {
  default = "172.17.0.1/16"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_ip_versions" {
  default = ["IPv4"]
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_load_balancer_profile_0_managed_outbound_ip_count" {
  default = 1
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_load_balancer_sku" {
  default = "standard"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_network_plugin" {
  default = "kubenet"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_outbound_type" {
  default = "loadBalancer"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_pod_cidr" {
  default = "10.244.0.0/16"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_network_profile_0_service_cidr" {
  default = "10.0.0.0/16"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_node_resource_group" {
  default = "rg-dev-aks-nodes"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_oms_agent_0_log_analytics_workspace_id" {
  default = "/subscriptions/713cac10-894c-4699-8407-412765959302/resourceGroups/softdocs-mgmt/providers/Microsoft.OperationalInsights/workspaces/softdocs-la"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_public_network_access_enabled" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_resource_group_name" {
  default = "rg-dev-aks"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_role_based_access_control_enabled" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_run_command_enabled" {
  default = true
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_sku_tier" {
  default = "Free"
}

variable "azurerm_kubernetes_cluster__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_tc_category" {
  default = "container"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_enable_auto_scaling" {
  default = true
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_kubelet_disk_type" {
  default = "OS"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_kubernetes_cluster_id" {
  default = "/subscriptions/a06ab73e-0da1-49d7-81cd-847d3e9618ac/resourceGroups/rg-dev-aks/providers/Microsoft.ContainerService/managedClusters/aks-dev"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_max_count" {
  default = 3
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_max_pods" {
  default = 110
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_min_count" {
  default = 1
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_mode" {
  default = "System"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_name" {
  default = "system"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_node_count" {
  default = 1
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_node_taints" {
  default = ["CriticalAddonsOnly=true:NoSchedule"]
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_orchestrator_version" {
  default = "1.24.6"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_os_disk_size_gb" {
  default = 128
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_os_disk_type" {
  default = "Managed"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_os_sku" {
  default = "Ubuntu"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_os_type" {
  default = "Linux"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_priority" {
  default = "Regular"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_scale_down_mode" {
  default = "Delete"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_spot_max_price" {
  default = -1
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_tc_category" {
  default = "container"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_system_vm_size" {
  default = "Standard_DS2_v2"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_enable_auto_scaling" {
  default = true
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_kubelet_disk_type" {
  default = "OS"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_kubernetes_cluster_id" {
  default = "/subscriptions/a06ab73e-0da1-49d7-81cd-847d3e9618ac/resourceGroups/rg-dev-aks/providers/Microsoft.ContainerService/managedClusters/aks-dev"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_max_count" {
  default = 3
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_max_pods" {
  default = 110
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_min_count" {
  default = 1
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_mode" {
  default = "User"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_name" {
  default = "user"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_node_count" {
  default = 1
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_orchestrator_version" {
  default = "1.24.6"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_os_disk_size_gb" {
  default = 128
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_os_disk_type" {
  default = "Managed"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_os_sku" {
  default = "Ubuntu"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_os_type" {
  default = "Linux"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_priority" {
  default = "Regular"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_scale_down_mode" {
  default = "Delete"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_spot_max_price" {
  default = -1
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_tc_category" {
  default = "container"
}

variable "azurerm_kubernetes_cluster_node_pool__subscriptions_a06ab73e_0da1_49d7_81cd_847d3e9618ac_resourcegroups_rg_dev_aks_providers_microsoft_containerservice_managedclusters_aks_dev_agentpools_user_vm_size" {
  default = "Standard_DS2_v2"
}

